### Rota para listar produtos
GET http://localhost:3000/produtos
Content-Type: application/json

###

### Rota para cadastrar produtos
POST http://localhost:3000/produtos
Content-Type: application/json

{
    "id":"1",
    "nome": "GTX 4090",
    "preco": 4450
}

###

### Pegar produto pelo id
GET http://localhost:3000/produtos/1
Content-Type: application/json

###