### Rota para listar produtos
GET http://localhost:3000/produtos
Content-Type: application/json

###

### Rota para cadastrar produtos
POST http://localhost:3000/produtos
Content-Type: application/json

{
    "id":"1",
    "nome": "GTX 4090",
    "preco": 4450
}

###

### Pegar produto pelo id
GET http://localhost:3000/produtos/1
Content-Type: application/json

###

### PUT - Editar Produto
PUT http://localhost:3000/produtos/1
Content-Type: application/json

{
    "novoNome": "RTX 3090 16gb",
    "novoPreco": 5500
}

###

### DELETE - DELETAR PRODUTO
DELETE http://localhost:3000/produtos/1
Content-Type: application/json

###

###DELETE TODOS OS PRODUTOS
DELETE http://localhost:3000/produtos
Content-Type: application/json

###